FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy the project
COPY . .

RUN ./node_modules/.bin/prisma generate

# No build step - Next.js runs in dev mode with hot reload
# with typecheck
# creat seed
CMD ["sh", "-c", "./node_modules/.bin/prisma migrate deploy && ./node_modules/.bin/prisma db seed && npm run dev"]